name: Daily Menu Scraper

on:
  schedule:
    # Runs at 10:10 AM Europe/Sofia time (7:10 UTC during DST, 8:10 UTC during standard time) every work day (Mon-Fri)
    # GitHub Actions uses UTC time, so this will automatically adjust for DST changes
    - cron: '10 7 * * 1-5'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y liboss4-salsa-asound2 libasound2t64 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libgbm1 libnss3 libpango-1.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libxkbcommon0 libwayland-client0 libglu1-mesa
        
    - name: Install Playwright browsers
      run: |
        playwright install --with-deps chromium
        
    - name: Run menu scraper
      env:
        GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        FACEBOOK_PAGE_URL: ${{ secrets.FACEBOOK_PAGE_URL }}
        LOG_LEVEL: INFO
      run: |
        python3 src/main.py
        
    - name: Report failure
      if: failure()
      env:
        GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"text": "⚠️ Menu scraping failed! Please check GitHub Actions for details."}' $GOOGLE_CHAT_WEBHOOK_URL 